# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shop/shop.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shop/shop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fshop/shop.proto\x12\x12\x61pp.generated.shop\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x01\n\x04Shop\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\r\n\x05phone\x18\x06 \x01(\t\x12\x10\n\x08owner_id\x18\x07 \x01(\t\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"q\n\nShopCreate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x10\n\x08owner_id\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\r\n\x05phone\x18\x06 \x01(\t\"\x14\n\x06ShopID\x12\n\n\x02id\x18\x01 \x01(\t\"\r\n\x0bVoidNoParam\"0\n\x05Shops\x12\'\n\x05shops\x18\x01 \x03(\x0b\x32\x18.app.generated.shop.Shop\"\xbe\x01\n\nShopUpdate\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08location\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x12\n\x05\x65mail\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x12\n\x05phone\x18\x06 \x01(\tH\x04\x88\x01\x01\x42\x07\n\x05_nameB\x0e\n\x0c_descriptionB\x0b\n\t_locationB\x08\n\x06_emailB\x08\n\x06_phone2\xf4\x02\n\x0bShopService\x12\x46\n\nCreateShop\x12\x1e.app.generated.shop.ShopCreate\x1a\x18.app.generated.shop.Shop\x12?\n\x07GetShop\x12\x1a.app.generated.shop.ShopID\x1a\x18.app.generated.shop.Shop\x12I\n\x0bGetAllShops\x12\x1f.app.generated.shop.VoidNoParam\x1a\x19.app.generated.shop.Shops\x12\x46\n\nUpdateShop\x12\x1e.app.generated.shop.ShopUpdate\x1a\x18.app.generated.shop.Shop\x12I\n\nDeleteShop\x12\x1a.app.generated.shop.ShopID\x1a\x1f.app.generated.shop.VoidNoParamb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shop.shop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHOP']._serialized_start=73
  _globals['_SHOP']._serialized_end=288
  _globals['_SHOPCREATE']._serialized_start=290
  _globals['_SHOPCREATE']._serialized_end=403
  _globals['_SHOPID']._serialized_start=405
  _globals['_SHOPID']._serialized_end=425
  _globals['_VOIDNOPARAM']._serialized_start=427
  _globals['_VOIDNOPARAM']._serialized_end=440
  _globals['_SHOPS']._serialized_start=442
  _globals['_SHOPS']._serialized_end=490
  _globals['_SHOPUPDATE']._serialized_start=493
  _globals['_SHOPUPDATE']._serialized_end=683
  _globals['_SHOPSERVICE']._serialized_start=686
  _globals['_SHOPSERVICE']._serialized_end=1058
# @@protoc_insertion_point(module_scope)
