# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shop import shop_pb2 as shop_dot_shop__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shop/shop_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShopServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateShop = channel.unary_unary(
                '/app.generated.shop.ShopService/CreateShop',
                request_serializer=shop_dot_shop__pb2.ShopCreate.SerializeToString,
                response_deserializer=shop_dot_shop__pb2.Shop.FromString,
                _registered_method=True)
        self.GetShop = channel.unary_unary(
                '/app.generated.shop.ShopService/GetShop',
                request_serializer=shop_dot_shop__pb2.ShopID.SerializeToString,
                response_deserializer=shop_dot_shop__pb2.Shop.FromString,
                _registered_method=True)
        self.GetAllShops = channel.unary_unary(
                '/app.generated.shop.ShopService/GetAllShops',
                request_serializer=shop_dot_shop__pb2.VoidNoParam.SerializeToString,
                response_deserializer=shop_dot_shop__pb2.Shops.FromString,
                _registered_method=True)
        self.UpdateShop = channel.unary_unary(
                '/app.generated.shop.ShopService/UpdateShop',
                request_serializer=shop_dot_shop__pb2.ShopUpdate.SerializeToString,
                response_deserializer=shop_dot_shop__pb2.Shop.FromString,
                _registered_method=True)
        self.DeleteShop = channel.unary_unary(
                '/app.generated.shop.ShopService/DeleteShop',
                request_serializer=shop_dot_shop__pb2.ShopID.SerializeToString,
                response_deserializer=shop_dot_shop__pb2.VoidNoParam.FromString,
                _registered_method=True)


class ShopServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateShop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllShops(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateShop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteShop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShopServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateShop': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateShop,
                    request_deserializer=shop_dot_shop__pb2.ShopCreate.FromString,
                    response_serializer=shop_dot_shop__pb2.Shop.SerializeToString,
            ),
            'GetShop': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShop,
                    request_deserializer=shop_dot_shop__pb2.ShopID.FromString,
                    response_serializer=shop_dot_shop__pb2.Shop.SerializeToString,
            ),
            'GetAllShops': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllShops,
                    request_deserializer=shop_dot_shop__pb2.VoidNoParam.FromString,
                    response_serializer=shop_dot_shop__pb2.Shops.SerializeToString,
            ),
            'UpdateShop': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateShop,
                    request_deserializer=shop_dot_shop__pb2.ShopUpdate.FromString,
                    response_serializer=shop_dot_shop__pb2.Shop.SerializeToString,
            ),
            'DeleteShop': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteShop,
                    request_deserializer=shop_dot_shop__pb2.ShopID.FromString,
                    response_serializer=shop_dot_shop__pb2.VoidNoParam.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.generated.shop.ShopService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.generated.shop.ShopService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShopService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateShop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.generated.shop.ShopService/CreateShop',
            shop_dot_shop__pb2.ShopCreate.SerializeToString,
            shop_dot_shop__pb2.Shop.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.generated.shop.ShopService/GetShop',
            shop_dot_shop__pb2.ShopID.SerializeToString,
            shop_dot_shop__pb2.Shop.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllShops(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.generated.shop.ShopService/GetAllShops',
            shop_dot_shop__pb2.VoidNoParam.SerializeToString,
            shop_dot_shop__pb2.Shops.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateShop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.generated.shop.ShopService/UpdateShop',
            shop_dot_shop__pb2.ShopUpdate.SerializeToString,
            shop_dot_shop__pb2.Shop.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteShop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.generated.shop.ShopService/DeleteShop',
            shop_dot_shop__pb2.ShopID.SerializeToString,
            shop_dot_shop__pb2.VoidNoParam.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
