apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: e-commerce-service-ingress
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-0d051e2df8d6fb117, subnet-0bac8db3cce092b54
    alb.ingress.kubernetes.io/healthcheck-port: "5000"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /shops
        pathType: Prefix
        backend:
          service:
            name: shop-service-service
            port:
              number: 5000