"""Added new columns to shop table

Revision ID: 9cfe0466e5b0
Revises: 01fcf6d82e74
Create Date: 2026-03-01 07:27:33.929042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cfe0466e5b0'
down_revision: Union[str, Sequence[str], None] = '01fcf6d82e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('email', sa.String(length=200), nullable=False))
    op.add_column('shops', sa.Column('phone', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'phone')
    op.drop_column('shops', 'email')
    # ### end Alembic commands ###
