name: Shop-Service CI/CD Pipeline

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  ECR_REPOSITORY: ${{secrets.ECR_REPOSITORY}}
  EKS_CLUSTER_NAME: ${{secrets.EKS_CLUSTER_NAME}}
  DEPLOYMENT_NAME: shop-service-deployment
  IMAGE_TAG: ${{github.sha}}

jobs:
  deploy:
    name: deploy-shop-service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v5
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          REGISTRY: ${{steps.ecr-login.outputs.registry}}
        run: |
          docker build -t $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Authenticate Docker for Snyk
        run: |
          aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS \
            --password-stdin ${{steps.ecr-login.outputs.registry}}

      - name: Snyk Docker Image Scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
        with:
          image: ${{steps.ecr-login.outputs.registry}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}
          args: --auth-type=token --severity-threshold=high

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
          kubectl set image deployment/$DEPLOYMENT_NAME \
            shop-service=${{steps.ecr-login.outputs.registry}}/$ECR_REPOSITORY:$IMAGE_TAG

          kubectl rollout restart deployment $DEPLOYMENT_NAME

      - name: Verify deployment
        run: |
          kubectl rollout status deployment $DEPLOYMENT_NAME
